# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DouYu' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DouYu

  pod 'Alamofire'
  pod 'SDWebImage'

  target 'DouYuTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DouYuUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
